version: '3.8'

services:
  api:
    build: .
    container_name: api
    ports:
      - "3000:3000"
    environment:
      - HOST=localhost
      - PORT=3000
      - DB_HOST=mongodb
      - DB_PORT=27017
      - DB_NAME=yourdbname
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - mongodb
      - redis

  mongodb:
    image: mongo
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secret

  redis:
    image: redis
    container_name: redis